export const schoolInfo = {
  name: "Collège Laferrière de Milot",
  shortName: "C.L.M",
  motto: "Le Gardien de l'Idéal de Grandeur",
  mottoKr: "Le Gardien de l'Idéal de Grandeur",
  mottoFr: "Le Gardien de l'Idéal de Grandeur",
  address: "Rue principale, Milot, Département du Nord, Haïti",
  phone: "+509 0000-0000",
  email: "info@college-laferriere.ht",
  hoursKr: "Lendi–Vandredi: 7:30 AM – 3:30 PM",
  hoursFr: "Lundi – Vendredi : 7h30 – 3h30 PM",
  saturdayHoursKr: "Samdi: 8:00 AM – 12:00 PM",
  saturdayHoursFr: "Samedi : 8h00 – 12h00 PM",
};

export const socialLinks = {
  facebook: "https://facebook.com",
  instagram: "https://instagram.com",
  whatsapp: "https://wa.me/50900000000",
  youtube: "https://youtube.com",
};

export const staffMembers = [
  { name: "Arslin Salomon", role: { fr: "Directeur Général", kr: "Direktè Jeneral" }, image: "Arslin Salomon.jpg" },
  { name: "Bruno Salomon", role: { fr: "Directeur Académique", kr: "Direktè Akademik" }, image: "Bruno Salomon.jpg" },
  { name: "Quetty Blaise", role: { fr: "Directrice Administrative", kr: "Direktris Administratif" }, image: "Quetty Blaise.jpg" },
  { name: "Obsnica Saint-Fleur", role: { fr: "Responsable Pédagogique", kr: "Responsab Pedagojik" }, image: "Obsnica Saint-Fleur.jpg" },
  { name: "Salomon Desamours", role: { fr: "Coordinateur des Études", kr: "Kowòdonatè Etid" }, image: "Salomon Desamours.jpg" },
  { name: "Obson Saint-Fleur", role: { fr: "Responsable Disciplinaire", kr: "Responsab Disiplin" }, image: "Obson Saint-Fleur.jpg" },
  { name: "Obertin Saint-Fleur", role: { fr: "Responsable Financier", kr: "Responsab Finans" }, image: "Obertin Saint-Fleur.jpg" },
  { name: "Bernice Saint-Fleur", role: { fr: "Conseillère Éducative", kr: "Konseye Edikatif" }, image: "Bernice Saint-Fleur.jpg" },
  { name: "Edouard Fils-Aime", role: { fr: "Responsable Logistique", kr: "Responsab Lojistik" }, image: "Edouard Fils-Aime.jpg" },
] as const;

export const openingClasses = [
  {
    title: "Petite Section",
    level: "Préscolaire I",
    fee: "6 000 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 500", "3e versement: 1 000", "4e versement: 500"],
    books: ["À Petits Pas 1 et 2", "Youpi ! Je colorie les animaux", "Youpi ! Je colorie les fêtes", "Youpi ! Je colorie les véhicules", "Je connais les fruits et les légumes"],
    supplies: ["4 cahiers doubles lignes", "1 boîte de crayons de couleur", "4 bristols bleus", "4 bristols rouges", "4 bristols d'autres couleurs", "2 couches par jour"],
  },
  {
    title: "Moyenne Section",
    level: "Préscolaire II",
    fee: "6 200 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 700", "3e versement: 1 000", "4e versement: 500"],
    books: ["La clé du français", "Ti Malice Cahier d'écriture", "Observation préscolaire 13e", "Mon imagier #1, #2 et #3", "Latéralisation", "Mes premiers pas vers l'écriture #1", "Pré-Math 1-2", "Pré-Calcul #1 et #2", "Espace #1 et #2", "Discrimination visuelle #1", "Schéma corporel", "Bravo ti malice"],
    supplies: ["12 petits cahiers doubles lignes et simples", "1 boîte crayons couleur", "6 crayons à mine de plombs", "4 bristols bleus", "4 bristols rouges", "4 bristols d'autres couleurs", "2 diapers par jour"],
  },
  {
    title: "Grande Section",
    level: "Préscolaire III",
    fee: "6 400 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 900", "3e versement: 1 000", "4e versement: 500"],
    books: ["Raisonnement logique #2", "Discrimination visuelle #2", "Bonjour 1", "Espace #2", "Youpi ! je sais écrire 1re année", "Youpi ! je sais lire 1re année", "Vive les maths #1", "Formes géométriques #2", "Contrôle Maths 1re année", "Pré-Calcul #2", "Contrôle Éveil 1ère Année"],
    supplies: ["12 petits cahiers doubles lignes et simples", "1 boîte de crayons couleur", "Crayon noir", "Crayon gomme", "Taille"],
  },
  {
    title: "1ère Année Fondamentale",
    level: "Fondamentale",
    fee: "5 000 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 000", "3e versement: 600", "4e versement: 400"],
    books: ["Mon livre d'éveil #1", "Youpi ! je sais lire #1", "Youpi ! je sais écrire #1", "La joie de lire #1 et 2", "Bien écrire #1", "Ma première grammaire", "Vive les maths #1", "Langage en fête", "Moi et les autres", "Premières notions d'Histoire", "Youpi ! je sais lire #2", "Méthode d'écriture #1", "Flute à bec"],
    supplies: ["6 cahiers doubles lignes", "6 cahiers quadrillé", "Crayons noir", "Gomme", "Plume", "1 boîte de crayon couleur"],
  },
  {
    title: "2ème Année Fondamentale",
    level: "Fondamentale",
    fee: "5 000 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 000", "3e versement: 600", "4e versement: 400"],
    books: ["Grammaire préparatoire FIC", "Je lis et j'écris le français #1 FIC", "Sciences sociales 2e AF Edition Dawill", "Wi mwen konn li 2e AF", "Bien écrire #2", "Mon livre d'Éveil 2e AF", "La joie de lire #2 et #3", "Youpi je sais lire #2", "Méthode d'écriture #2", "Vive les Maths #2 FIC", "Vocabulaire FIC #2", "Mes droits et devoirs", "Sciences expérimentales Ed Dawill"],
    supplies: ["18 cahiers de 36 pages", "1 boîte de crayon couleur", "Règle", "Gomme", "Plume", "Crayon noir", "10 cahiers à double ligne"],
  },
  {
    title: "3ème Année Fondamentale",
    level: "Fondamentale",
    fee: "5 000 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 000", "3e versement: 600", "4e versement: 400"],
    books: ["Histoire de mon pays #1", "Mes droits et mes devoirs", "Orthographe 3e AF", "Mon livre de vocabulaire 3e AF", "Méthode d'écriture #3", "La joie de lire #3", "Mon livre de Géographie #1", "Sciences Sociales Edition Dawill #2", "Sciences Expérimentales Edition Dawill #3", "Mon livre de sciences #1", "Wi mwen konn li", "Vive les maths #3", "Je lis et j'écris le français #2", "À la rencontre de la Grammaire #1", "Mieux parler #1", "Dictée cours préparatoire F.I.C"],
    supplies: ["12 cahiers de 18 pages", "18 cahiers de 36 pages", "1 boîte de crayons de couleur", "1 règle", "1 gomme", "1 plume", "1 crayon noir"],
  },
  {
    title: "4ème Année Fondamentale",
    level: "Fondamentale",
    fee: "5 200 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 200", "3e versement: 600", "4e versement: 400"],
    books: ["Histoire de mon pays #2", "Mon livre de Géographie #1", "Mon livre de sciences #1", "Nous les enfants d'aujourd'hui", "Pour lire avec plaisir #2", "Vocabulaire 4e ou 5e AF - Livre 2", "À la rencontre de la Grammaire #2", "Mon 2e livre d'orthographe", "Mieux parler #2", "Wi mwen konn li 4e ou 5e ane", "Vive les maths #4", "Dictée cours élémentaire FIC", "Méthode d'écriture #4"],
    supplies: ["12 gros cahiers de 36 pages", "3 cahiers Dominique", "Dictionnaire de l'écolier", "Instruments de géométrie", "Gomme", "Plume", "Règle"],
  },
  {
    title: "5ème Année Fondamentale",
    level: "Fondamentale",
    fee: "5 200 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 200", "3e versement: 600", "4e versement: 400"],
    books: ["Histoire de mon pays 5e et 6e AF", "Mon livre de Géographie #2", "Nous, les citoyens de demain", "Mon livre de sciences #2", "Mon vocabulaire #3", "Pour lire avec plaisir #3", "Wi mwen konn li 5e liv", "Mieux parler #3", "Méthode d'écriture #5", "À la rencontre de la Grammaire #3", "Mon livre d'orthographe #3", "Vive les maths #5"],
    supplies: ["3 cahiers Dominique", "10 cahiers 36 pages", "3 cahiers double ligne", "Dictionnaire de l'écolier", "Instruments géométriques", "Plume", "Gomme"],
  },
  {
    title: "6ème Année Fondamentale",
    level: "Fondamentale",
    fee: "5 200 gourdes",
    payments: ["1er versement: 3 000", "2e versement: 1 200", "3e versement: 600", "4e versement: 400"],
    books: ["Histoire de mon pays, Haïti 3 et 4", "Mon livre de Géographie #2", "Nous les citoyens de demain", "Mon livre de sciences #2", "Mon livre de vocabulaire 5e et 6e AF", "Pour lire avec plaisir #4", "Mieux parler #4", "Méthode d'écriture #6", "À la rencontre de la Grammaire #3", "Mon 3e livre d'orthographe", "Vive les maths 6", "Vocabulaire #3", "Dictée cours moyen FIC", "Wi mwen konn li"],
    supplies: ["3 cahiers Dominique", "10 cahiers 36 pages", "3 cahiers double ligne", "Dictionnaire Larousse", "Instruments géométriques", "Plume", "Gomme"],
  },
];
