"use client";

import { motion } from "framer-motion";
import { BookOpen, BrainCircuit, ClipboardCheck, Dumbbell, Globe2, GraduationCap, HeartHandshake, Hourglass, Landmark, LibraryBig, Palette, Send, ShieldCheck, Smartphone, Sprout, UsersRound } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import cardLogo from "../../assets/cards.jpeg";
import classroomImage from "../../assets/elevesenlasse.png";
import heroImage from "../../assets/hero.jpeg";
import cultureImage from "../../assets/journeeculturelle.png";
import labImage from "../../assets/laboratoire.png";
import libraryImage from "../../assets/lecture.png";
import sportImage from "../../assets/sport.png";
import techImage from "../../assets/tech.png";
import teamworkImage from "../../assets/travialequipe.png";
import celebrationImage from "../../assets/graduate.png";
import { useLanguage } from "@/hooks/useLanguage";
import type { LucideIcon } from "lucide-react";

const fade = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-80px" }, transition: { duration: 0.55 } };
const modernIconBadge = "grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-[#0B3D5C] to-[#052E46] text-white shadow-lg shadow-[#0B3D5C]/20 ring-1 ring-white/70 transition duration-300 group-hover:scale-105 group-hover:rotate-3 group-even:from-[#E5AD32] group-even:to-[#B8790E]";
const smallIconBadge = "flex items-center gap-3 rounded-2xl bg-white/75 px-4 py-3 text-[#0B3D5C] shadow-sm ring-1 ring-[#E5AD32]/20 transition hover:-translate-y-1 hover:shadow-md";
const heroFeatures = [{ icon: BookOpen, title: "Excellence académique", text: "Enseignement rigoureux" }, { icon: UsersRound, title: "Valeurs et discipline", text: "Respect, intégrité, responsabilité" }, { icon: Sprout, title: "Ancrés dans nos racines", text: "Fiers de notre culture" }, { icon: Globe2, title: "Ouverts sur le monde", text: "Préparés pour l’avenir" }] as const;
const values = [{ icon: ShieldCheck, label: "Discipline" }, { icon: LibraryBig, label: "Savoir" }, { icon: Landmark, label: "Culture" }, { icon: HeartHandshake, label: "Service" }] as const;
const programIcons = [BrainCircuit, BookOpen, Smartphone, Palette, Dumbbell, UsersRound] as const;
const galleryImages = [classroomImage, teamworkImage, cultureImage, labImage, sportImage, libraryImage, celebrationImage, techImage] as const;

function MetricCard({ icon: Icon, value, suffix, label, className }: { icon: LucideIcon; value: number; suffix: string; label: string; className?: string }) {
  return <motion.div {...fade} className={`absolute z-20 w-32 rounded-2xl border border-white/80 bg-white/90 p-4 shadow-xl shadow-[#0B3D5C]/10 backdrop-blur sm:w-36 ${className ?? ""}`}><Icon className="mb-2 size-7 text-[#D79B16]" aria-hidden="true" /><strong className="block font-heading text-2xl font-black text-[#0B3D5C]">{value}{suffix}</strong><span className="text-xs font-extrabold leading-tight text-slate-600">{label}</span></motion.div>;
}

export default function Home() {
  const { t } = useLanguage();
  return <main id="main">
    <section id="home" className="relative overflow-hidden text-white"><div className="relative flex min-h-svh flex-col justify-center px-4 pb-16 pt-28 sm:min-h-[620px] sm:pb-20 sm:pt-32 md:min-h-[680px] md:pb-36"><Image src={heroImage} alt="Citadelle Laferrière overlooking the mountains near Milot, Haiti" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#082F49]/92 via-[#0B3D5C]/66 to-[#0B3D5C]/10" /><div className="absolute inset-0 bg-gradient-to-t from-[#082F49]/65 via-transparent to-transparent" /><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="relative mx-auto w-full max-w-7xl"><div className="max-w-3xl text-left"><p className="mb-4 text-xs font-black uppercase tracking-[0.22em] text-[#E5AD32] sm:text-sm">{t.hero.eyebrow}</p><h1 className="font-heading text-3xl font-black leading-[1.08] tracking-tight min-[380px]:text-4xl sm:text-5xl md:text-6xl lg:text-7xl">{t.hero.headline}</h1><p className="mt-4 max-w-2xl text-sm font-semibold leading-relaxed text-blue-50 sm:text-base md:text-lg">{t.hero.text}</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/admissions" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#E5AD32] px-6 py-3.5 text-sm font-extrabold text-[#0B3D5C] shadow-xl transition hover:-translate-y-1 sm:text-base"><GraduationCap className="size-5" />{t.hero.cta}</Link><Link href="/#about" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/60 bg-white/10 px-6 py-3.5 text-sm font-extrabold text-white backdrop-blur transition hover:-translate-y-1 sm:text-base"><Send className="size-5 text-[#E5AD32]" />{t.hero.secondary}</Link></div></div></motion.div></div><div className="relative z-20 mx-auto -mt-24 hidden max-w-6xl px-4 pb-4 md:block"><div className="grid grid-cols-4 gap-4 rounded-2xl border border-white/20 bg-[#07314B]/82 px-7 py-5 shadow-2xl backdrop-blur-xl">{heroFeatures.map(({ icon: Icon, title, text }) => <div key={title} className="group flex items-center gap-4 rounded-xl p-2 transition hover:bg-white/10"><Icon className="size-9 shrink-0 text-[#E5AD32]" /><div><h3 className="text-sm font-extrabold">{title}</h3><p className="text-sm text-white/90">{text}</p></div></div>)}</div></div></section>
    <section id="about" className="section-pad relative overflow-hidden border-b border-[#E5AD32]/20 bg-[#FFFDF8]"><div className="relative mx-auto max-w-7xl"><div className="grid items-center gap-12 lg:grid-cols-2"><motion.div {...fade}><p className="text-sm font-black uppercase tracking-[0.25em] text-[#D79B16]">{t.nav.about}</p><h2 className="mt-3 font-heading text-3xl font-black text-[#0B3D5C] sm:text-4xl md:text-5xl">{t.about.title}</h2><div className="mt-6 space-y-4 text-base leading-7 text-slate-600 sm:text-lg">{t.about.intro.map((p, index) => <p key={index}>{p}</p>)}</div></motion.div><motion.div {...fade} className="relative mx-auto h-[36rem] w-full max-w-md sm:h-[31rem] sm:max-w-lg lg:h-[30rem]"><div className="absolute left-1/2 top-[40%] z-10 grid size-44 -translate-x-1/2 -translate-y-1/2 place-items-center overflow-hidden rounded-full border border-white/60 bg-white/70 text-center shadow-2xl backdrop-blur sm:top-1/2 sm:size-52 md:size-56"><Image src={cardLogo} alt="" fill sizes="224px" className="object-cover opacity-10" /><div className="relative px-4"><strong className="font-heading text-5xl font-black text-[#16425B]">{t.stats[1].value}{t.stats[1].suffix}</strong><p className="mt-1 text-sm font-bold text-slate-600">{t.stats[1].label}</p></div></div><MetricCard icon={Hourglass} {...t.stats[0]} className="right-4 top-0 sm:right-8 sm:top-5" /><MetricCard icon={GraduationCap} {...t.stats[2]} className="bottom-32 left-4 sm:bottom-16 sm:left-8" /><MetricCard icon={ClipboardCheck} {...t.stats[3]} className="bottom-0 right-4 sm:bottom-8 sm:right-4" /></motion.div></div><div className="mt-12 grid grid-cols-2 gap-4 text-[#0B3D5C] sm:flex sm:flex-wrap sm:items-center sm:gap-7">{values.map(({ icon: Icon, label }) => <span key={label} className={smallIconBadge}><Icon className="size-5 text-[#7DA4BD]" /><span className="text-sm font-extrabold">{label}</span></span>)}</div></div></section>
    <section id="programs" className="border-b border-[#E5AD32]/20 bg-[#FAF8F2] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><motion.div {...fade} className="mx-auto max-w-3xl text-center"><h2 className="font-heading text-3xl font-black text-[#0B3D5C] sm:text-5xl">{t.programsTitle}</h2><div className="mx-auto mt-3 h-1 w-16 rounded-full bg-[#E5AD32]" /><p className="mt-3 text-sm font-semibold text-[#31536A]">{t.programsText}</p></motion.div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{t.programs.slice(0, 6).map((program, index) => { const ProgramIcon = programIcons[index] ?? BookOpen; return <article key={program.title} className="group flex gap-5 rounded-2xl border border-white bg-white p-6 shadow-[0_18px_40px_rgba(11,61,92,0.10)] transition duration-300 hover:-translate-y-2"><span className={modernIconBadge}><ProgramIcon className="size-8" /></span><div><h3 className="font-heading text-xl font-black text-[#0B3D5C]">{program.title}</h3><p className="mt-2 leading-6 text-slate-600">{program.description}</p></div></article>; })}</div></div></section>
    <section className="bg-[#EAF6FA] px-4 py-10"><motion.div {...fade} className="mx-auto flex max-w-7xl flex-col gap-6 rounded-3xl bg-white p-6 shadow-xl md:flex-row md:items-center md:justify-between md:p-8"><div className="flex gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-[#16425B] text-[#E5AD32]"><BookOpen /></span><div><h2 className="font-heading text-2xl font-black text-[#16425B]">{t.classesCta.heading}</h2><p className="mt-2 text-slate-600">{t.classesCta.text}</p><p className="mt-3 text-sm font-semibold text-[#31536A]">{t.classesCta.helpText} <Link className="text-[#16425B] underline" href="/admissions">{t.classesCta.contactButton}</Link></p></div></div><Link href="/classes" className="inline-flex justify-center rounded-full bg-[#E5AD32] px-8 py-4 font-black text-[#16425B] shadow-lg transition hover:-translate-y-1">{t.classesCta.button}</Link></motion.div></section>
    <section id="vie-scolaire" className="section-pad bg-slate-50"><div className="mx-auto max-w-7xl"><motion.div {...fade} className="text-center"><h2 className="font-heading text-3xl font-black text-[#16425B] sm:text-4xl">{t.galleryTitle}</h2><p className="mx-auto mt-4 max-w-2xl text-slate-700">{t.galleryText}</p></motion.div><div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-4">{t.gallery.map((caption, i) => <motion.figure {...fade} key={caption} className="group relative min-h-[180px] overflow-hidden rounded-2xl bg-slate-200 shadow-md sm:min-h-[230px]"><Image src={galleryImages[i]} alt="" fill sizes="(min-width: 1024px) 25vw, 50vw" className="object-cover transition-transform duration-300 group-hover:scale-105" /><figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent px-4 pb-4 pt-14 text-sm font-bold text-white sm:text-base">{caption}</figcaption></motion.figure>)}</div><div className="mt-6 flex justify-center gap-2" aria-hidden="true">{[0,1,2,3].map((d)=><span key={d} className={`size-2.5 rounded-full ${d===0?'bg-[#16425B]':'bg-[#81C3D7]'}`} />)}</div><div className="mt-8 text-center"><Link href="/#vie-scolaire" className="inline-flex rounded-full bg-[#16425B] px-7 py-3 font-bold text-white">{t.vieScolaire.seeAll}</Link></div></div></section>
    <section className="bg-white px-4 py-10"><div className="mx-auto flex max-w-4xl flex-col justify-center gap-4 sm:flex-row"><Link href="/equipe" className="rounded-2xl border border-[#D9DCD6] bg-[#F7F8F5] px-6 py-4 text-center font-heading font-black text-[#16425B] shadow-sm hover:-translate-y-1 hover:shadow-md">{t.bottomCta.staff}</Link><Link href="/admissions" className="rounded-2xl bg-[#16425B] px-6 py-4 text-center font-heading font-black text-white shadow-sm hover:-translate-y-1 hover:shadow-md">{t.bottomCta.admissions}</Link></div></section>
  </main>;
}
